### ISSUE TITLE
`rebootTime` -> Integer cannot be cast to Long

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [juliansteenbakker/nordic_dfu#105]
With version 6.1.0, I'm facing the following error:
```
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): Failed to handle method call
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at dev.steenbakker.nordicdfu.NordicDfuPlugin.initiateDfu(NordicDfuPlugin.kt:88)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at dev.steenbakker.nordicdfu.NordicDfuPlugin.onMethodCall(NordicDfuPlugin.kt:52)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at android.app.ActivityThread.main(ActivityThread.java:7959)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#dev.steenbakker.nordic_dfu/method(31160): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
E/flutter (31160): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.Integer cannot be cast to java.lang.Long, null, java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/flutter (31160): 	at dev.steenbakker.nordicdfu.NordicDfuPlugin.initiateDfu(NordicDfuPlugin.kt:88)
E/flutter (31160): 	at dev.steenbakker.nordicdfu.NordicDfuPlugin.onMethodCall(NordicDfuPlugin.kt:52)
E/flutter (31160): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (31160): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (31160): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (31160): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (31160): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (31160): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (31160): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (31160): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (31160): 	at android.app.ActivityThread.main(ActivityThread.java:7959)
E/flutter (31160): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (31160): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (31160): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
E/flutter (31160): )
E/flutter (31160): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (31160): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (31160): <asynchronous suspension>
E/flutter (31160): 
```

Looks like this line needs to be replaced:
```kotlin
val rebootTime = call.argument<Long>("rebootTime")
```
With this one:
```kotlin
val rebootTime = call.argument<Int>("rebootTime")?.toLong()
```

Could you please have a look @juliansteenbakker?

**Comment by juliansteenbakker** [comment]
This issue has been fixed in v6.1.2
