### ISSUE TITLE
dfu isn't starting or starting late

### ISSUE THREAD

**Issue by AdemYavuzCelik** [juliansteenbakker/nordic_dfu#137]
nordic dfu app can update the device but this library cant update.  Logs below. These events keep happening consistently, resulting in either not starting or starting late. i added reboot time but it didnt work

D/BluetoothLeScanner(32012): could not find callback wrapper
D/BluetoothAdapter(32012): isLeEnabled(): ON
D/BluetoothLeScanner(32012): onScannerRegistered() - status=6 scannerId=-1 mScannerId=0
D/BluetoothAdapter(32012): isLeEnabled(): ON
D/BluetoothLeScanner(32012): could not find callback wrapper
D/BluetoothAdapter(32012): isLeEnabled(): ON
D/BluetoothLeScanner(32012): onScannerRegistered() - status=6 scannerId=-1 mScannerId=0
D/BluetoothGatt(32012): onClientConnectionState() - status=0 clientIf=8 device=DE:F2:E6:5C:E3:83
I/DfuBaseService(32012): Connected to GATT server
D/BluetoothGatt(32012): discoverServices() - device: DE:F2:E6:5C:E3:83
I/DfuBaseService(32012): Action received: android.bluetooth.device.action.ACL_CONNECTED
I/DfuBaseService(32012): Attempting to start service discovery... succeed
D/BluetoothGatt(32012): onConfigureMTU() - Device=DE:F2:E6:5C:E3:83 mtu=30 status=0
W/BluetoothGatt(32012): Unhandled exception in callback
/BluetoothGatt(32012): Unhandled exception in callback
W/BluetoothGatt(32012): java.lang.NullPointerException: Attempt to invoke virtual method 'void no.nordicsemi.android.dfu.DfuBaseService.sendLogBroadcast(int, java.lang.String)' on a null object reference
W/BluetoothGatt(32012): 	at no.nordicsemi.android.dfu.BaseDfuImpl$BaseBluetoothGattCallback.onMtuChanged(BaseDfuImpl.java:211)
W/BluetoothGatt(32012): 	at no.nordicsemi.android.dfu.DfuBaseService$5.onMtuChanged(DfuBaseService.java:1007)
W/BluetoothGatt(32012): 	at android.bluetooth.BluetoothGatt$1$13.run(BluetoothGatt.java:770)
W/BluetoothGatt(32012): 	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:948)
W/BluetoothGatt(32012): 	at android.bluetooth.BluetoothGatt.-$$Nest$mrunOrQueueCallback(Unknown Source:0)
W/BluetoothGatt(32012): 	at android.bluetooth.BluetoothGatt$1.onConfigureMTU(BluetoothGatt.java:765)
W/BluetoothGatt(32012): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:353)
W/BluetoothGatt(32012): 	at android.os.Binder.execTransactInternal(Binder.java:1290)
W/BluetoothGatt(32012): 	at android.os.Binder.execTransact(Binder.java:1249)
D/BluetoothAdapter(32012): isLeEnabled(): ON
D/BluetoothLeScanner(32012): could not find callback wrapper
D/BluetoothAdapter(32012): isLeEnabled(): ON
D/BluetoothLeScanner(32012): onScannerRegistered() - status=6 scannerId=-1 mScannerId=0
D/BluetoothGatt(32012): onConnectionUpdated() - Device=DE:F2:E6:5C:E3:83 interval=6 latency=0 timeout=500 status=0
D/BluetoothGatt(32012): onSearchComplete() = Device=DE:F2:E6:5C:E3:83 Status=0
I/DfuBaseService(32012): Services discovered
I/DfuImpl (32012): Buttonless service without bond sharing found -> SDK 13 or newer
I/DfuImpl (32012): Enabling indications...
D/BluetoothGatt(32012): setCharacteristicNotification() - uuid: 8ec90003-f315-4f60-9fb8-838830daea50 enable: true
I/DfuImpl (32012): Sending Enter Bootloader (Op Code = 1)
I/DfuImpl (32012): Response received (Op Code = 1, Status = 1)
I/DfuBaseService(32012): Disconnecting from the device...
D/BluetoothGatt(32012): cancelOpen() - device: DE:F2:E6:5C:E3:83

**Comment by juliansteenbakker** [comment]
Please let me know if this issue still exists in the latest v7.2.0
