### ISSUE TITLE
Connect SDK w/o nrfutils ?

### ISSUE THREAD

**Issue by thomasklaush** [juliansteenbakker/nordic_dfu#149]
Can I use this library for firmware with nrf connect sdk?

When I build the firmware, a -zip is available, but the file does not work:

```
D/CompatibilityChangeReporter(17466): Compat change id reported: 160794467; UID 10485; state: ENABLED
W/DfuArchiveInputStream(17466): Manifest failed to be parsed. Did you add 
W/DfuArchiveInputStream(17466): -keep class no.nordicsemi.android.dfu.** { *; }
W/DfuArchiveInputStream(17466): to your proguard rules?
E/DfuBaseService(17466): An exception occurred while calculating file size
E/DfuBaseService(17466): java.io.IOException: The ZIP file must contain an Application, a Soft Device and/or a Bootloader.
E/DfuBaseService(17466): 	at no.nordicsemi.android.dfu.internal.ArchiveInputStream.<init>(ArchiveInputStream.java:279)
E/DfuBaseService(17466): 	at no.nordicsemi.android.dfu.DfuBaseService.openInputStream(DfuBaseService.java:1470)
E/DfuBaseService(17466): 	at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1206)
E/DfuBaseService(17466): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
E/DfuBaseService(17466): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/DfuBaseService(17466): 	at android.os.Looper.loopOnce(Looper.java:232)
E/DfuBaseService(17466): 	at android.os.Looper.loop(Looper.java:317)
E/DfuBaseService(17466): 	at android.os.HandlerThread.run(HandlerThread.java:68)
```

nrf utils is not working on Win11 (At least not on mine)

**Comment by juliansteenbakker** [comment]
i think you should use mcumgr_flutter
